### PR TITLE
Added a few more currencies

### PR DESCRIPTION
**Pull request by SYoder1**
- Barbadian Dollar
- Bolivian Boliviano
- Bahamian Dollar
- Costa Rican Colón
- Dominican Peso
- Guatemalan Quetzal
- honduran lempira
- jamaican dollar
- nicaraguan Córdoba
- panamanian balboa 
- peruvian Nuevo Sol
- paraguayan Guaraní
- salvadoran Colón
- uruguayan Peso

### CODE REVIEW

**Comment by SYoder1** [comment]
@btroia 👀 for visibility

**Comment by btroia** [comment]
@SYoder1 Thanks for the PR! If you could please add tests for these currencies to the [test file](https://github.com/AwesomeLabs/react-native-format-currency/blob/main/test/test.js) I'll then merge

**Comment by SYoder1** [comment]
@btroia Tests have been added

**Comment by btroia** [comment]
> @btroia Tests have been added

Thanks!

**Pull request merged**
